Sat Apr 25 02:37:47 UTC 2015 a/aaa_elflibs-14.1-x86_64-6.txz:  Rebuilt.   Added libstdc++.so.6.0.20. a/cxxlibs-6.0.18-x86_64-1.txz:  Removed. a/mkinitrd-1.4.8-x86_64-4.txz:  Rebuilt.   In mkinitrd_command_generator.sh:  fixed the kernel version detection, and   muted the error about missing /sys hcd module directories.   Blacklisted iphone-set-info to prevent the initrd from uselessly bloating.   Thanks to Ryan P.C. McQuen, Eric Hameleers, and Dan Church. d/gcc-4.9.2-x86_64-2.txz:  Rebuilt.   Recompiled with --enable-install-libiberty.  Thanks to fskmh. d/gcc-g++-4.9.2-x86_64-2.txz:  Rebuilt. d/gcc-gfortran-4.9.2-x86_64-2.txz:  Rebuilt. d/gcc-gnat-4.9.2-x86_64-2.txz:  Rebuilt. d/gcc-go-4.9.2-x86_64-2.txz:  Rebuilt. d/gcc-java-4.9.2-x86_64-2.txz:  Rebuilt. d/gcc-objc-4.9.2-x86_64-2.txz:  Rebuilt. d/llvm-3.6.0-x86_64-2.txz:  Rebuilt.   Fixed overly restrictive permissions on c++-analyzer, ccc-analyzer,   scan-build, set-xcode-analyzer, and scan-view.   Thanks to Ricardo Nabinger Sanchez. l/gc-7.4.2-x86_64-2.txz:  Rebuilt.   Patched to fix "undefined reference to `GC_setup_mark_lock'", noticed while   building inkscape.  Thanks to Matteo Bernardini. l/libmpc-1.0.3-x86_64-1.txz:  Upgraded.   Thanks to fskmh. l/lzo-2.09-x86_64-1.txz:  Upgraded. l/netpbm-10.66.02-x86_64-2.txz:  Rebuilt.   Fixed libnetpbm.so symlink.  Thanks to Matteo Bernardini. n/crda-3.18-x86_64-2.txz:  Rebuilt.   Ensure libreg.so is installed in the proper lib directory.   Thanks to Robby Workman. n/iproute2-3.18.0-x86_64-2.txz:  Rebuilt.   Properly handle /etc/iproute2/nl_protos.new config file.   Thanks to Wim Speekenbrink. n/libgpg-error-1.18-x86_64-2.txz:  Rebuilt.   Compress info file, and remove /usr/info/dir from package.   Thanks to Edward Trumbo.   Don't build static library. n/php-5.6.8-x86_64-2.txz:  Rebuilt.   Fixed permissions on /etc/httpd/.  Thanks to Francisco Ambrozio. n/rsync-3.1.1-x86_64-1.txz:  Upgraded.